# Workflow name
name: Cypress-Tests

# Trigger workflow on all pull requests to develop
on:
    pull_request:
      branches:
        - develop
      
# Job information
jobs:
  test:
    # Test name
    name: Cypress-Tests
    # Operating system to run the worflow on
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
      # Get code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install the dependencies
      - name: Install Dependencies
        run: npm install
        
      # Run the build
      - name: Run Build
        run: npm run build

      # Run component tests
      - name: Run Component Tests
        run: npm run test-component
