name: Deploy-to-Render

on:
    pull_request:
      branches:
        - main
    push:
      branches: 
        - main
    
       
jobs:
    ci:
      name: Deploy-to-Render
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Test
          run: |
            npm install
            npm run test-component

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
