# Workflow name
name: Deploy-to-Render

# Trigger workflow on all pull requests and pushes to main
on:
    pull_request:
      branches:
        - main
    push:
      branches: 
        - main
    
# Job information       
jobs:
    ci:
      # CI name
      name: Deploy-to-Render
      # Operating system to run the worflow on
      runs-on: ubuntu-latest
      # Steps to perform
      steps:
        # Get code from the repository
        - name: Checkout code
          uses: actions/checkout@v4
        # Run install and check the component test to verify it
        - name: Test
          run: |
            npm install
            npm run test-component
        # If the test passes, deploy to Render if on the main branch
        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
